[package]
name = "research_factory"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }
interfaces = { path = "../interfaces" }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
grant_treasury = { path = "../grant_treasury" }
university_registry = { path = "../university_registry" }
research_project = { path = "../research_project" }
